name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: menghellocontainerregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t menghellocontainerregistry.azurecr.io/hello-aks:latest .
          docker push menghellocontainerregistry.azurecr.io/hello-aks:latest

      - name: Set up kubectl
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name:  hello-cluster
          resource-group: aks-course-rg

      - name: Deploy to AKS
        run: |
            kubectl set image deployment -l app=hello-app container-xyz=menghellocontainerregistry.azurecr.io/hello-aks:latest